name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16.x, 18.x]
        vscode-version: [stable, insiders]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint
      run: npm run lint
    
    - name: Compile
      run: npm run compile
    
    - name: Run tests
      uses: coactions/setup-xvfb@v1
      with:
        run: npm test
      env:
        VSCODE_VERSION: ${{ matrix.vscode-version }}
    
    - name: Upload coverage reports
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '18.x' && matrix.vscode-version == 'stable'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        fail_ci_if_error: true
        verbose: true

  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check code formatting
      run: npx prettier --check "src/**/*.ts"
    
    - name: Type check
      run: npm run compile -- --noEmit
    
    - name: Security audit
      run: npm audit --audit-level=moderate

  build:
    needs: [test, code-quality]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install vsce
      run: npm install -g @vscode/vsce
    
    - name: Package extension
      run: vsce package
    
    - name: Upload VSIX
      uses: actions/upload-artifact@v3
      with:
        name: django-power-tools-vsix
        path: '*.vsix'